version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nolan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: loldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
