version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nolan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: loldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python-app:
    build: ./path/to/python/app
    environment:
      POSTGRES_USER: nolan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: loldb
      POSTGRES_HOST: postgres
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    volumes:
      - ./path/to/python/app:/usr/src/app

volumes:
  pgdata:
