version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: nolan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: loldb
    volumes:
      - pgdata:/var/lib/postgresql/data

  python-app:
    build: .  # Set the build context to the project root
    environment:
      POSTGRES_USER: nolan
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: loldb
      POSTGRES_HOST: postgres
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app  # Mount the src directory

volumes:
  pgdata:
