CREATE TABLE participant_frames (
    frameId SERIAL PRIMARY KEY,
    matchId VARCHAR(255),
    participantId INT,
    timestamp BIGINT,
    level INT,
    currentGold INT,
    totalGold INT,
    xp INT,
    minionsKilled INT,
    jungleMinionsKilled INT,
    timeEnemySpentControlled INT,
    -- Champion Stats
    abilityHaste INT,
    abilityPower INT,
    armor INT,
    armorPen INT,
    armorPenPercent FLOAT,
    attackDamage INT,
    attackSpeed INT,
    bonusArmorPenPercent FLOAT,
    bonusMagicPenPercent FLOAT,
    ccReduction INT,
    cooldownReduction INT,
    health INT,
    healthMax INT,
    healthRegen INT,
    lifesteal INT,
    magicPen INT,
    magicPenPercent FLOAT,
    magicResist INT,
    movementSpeed INT,
    omnivamp INT,
    physicalVamp INT,
    power INT,
    powerMax INT,
    powerRegen INT,
    spellVamp INT,
    -- Damage Stats
    magicDamageDone INT,
    magicDamageDoneToChampions INT,
    magicDamageTaken INT,
    physicalDamageDone INT,
    physicalDamageDoneToChampions INT,
    physicalDamageTaken INT,
    totalDamageDone INT,
    totalDamageDoneToChampions INT,
    totalDamageTaken INT,
    trueDamageDone INT,
    trueDamageDoneToChampions INT,
    trueDamageTaken INT,
    -- Position
    positionX INT,
    positionY INT,
    FOREIGN KEY (matchId) REFERENCES match_metadata(matchId),
    FOREIGN KEY (matchId, participantId) REFERENCES player_match_data(matchId, participantId)
);
